/**:
  ros__parameters:
    # Lidar settings
    use_lidar: false
    # QoS settings
    input_qos: "SENSOR_DATA"
    # Map clearing settings
    map_clearing_frame_id: "base_footprint"
    # Rviz visualization
    slice_visualization_attachment_frame_id: "camera_link"

    static_mapper:
      esdf_slice_height: 0.30
      esdf_slice_min_height: 0.30
      esdf_slice_max_height: 0.50

    dynamic_mapper:
      esdf_slice_height: 0.30
      esdf_slice_min_height: 0.30
      esdf_slice_max_height: 0.50
