# Use an appropriate base image compatible with Isaac ROS and ZED SDK
ARG BASE_IMAGE
FROM ${BASE_IMAGE}

# Define arguments for the ZED SDK version (if needed)
ARG ZED_SDK_MAJOR=4
ARG ZED_SDK_MINOR=1

# Install necessary dependencies
RUN sudo apt-get update && sudo apt-get install -y \
    lsb-release wget less zstd udev sudo apt-transport-https \
    libgeographic-dev ros-humble-geographic-info \
    ros-humble-nmea-msgs ros-humble-robot-localization \
    ros-humble-xacro && \
    sudo rm -rf /var/lib/apt/lists/* && \
    sudo apt-get clean

RUN mkdir -p /opt/zed/

# The zed installation script expects to be run as non-root user and needs the USER ENV variable to be set
ENV USER=${USERNAME}
USER ${USERNAME}
    
COPY scripts/install-zed-x86_64.sh /opt/zed/install-zed-x86_64.sh
COPY scripts/install-zed-aarch64.sh /opt/zed/install-zed-aarch64.sh
    
RUN sudo chmod +x /opt/zed/install-zed-x86_64.sh
RUN sudo chmod +x /opt/zed/install-zed-aarch64.sh
    
RUN if [ "$(uname -m)" = "x86_64" ]; then \
    /opt/zed/install-zed-x86_64.sh; \
  else \
    /opt/zed/install-zed-aarch64.sh; \
  fi
    
    # Revert to root user
USER root
