/**:
  ros__parameters:
    # miscellaneous
    voxel_size: 0.05
    num_cameras: 1
    use_tf_transforms: true
    # multi mapper
    mapping_type: "static_tsdf"  # ["static_tsdf", "static_occupancy"]
    connected_mask_component_size_threshold: 2000

    # Parameters governing frequency of different processing steps in the reconstruction pipeline.
    # Processing happens every n:th tick_period. <=0 means that no processing take place
    tick_period_ms: 10
    integrate_depth_rate_hz: 40.0
    integrate_color_rate_hz: 5.0
    integrate_lidar_rate_hz: 40.0
    update_mesh_rate_hz: 5.0
    update_esdf_rate_hz: 10.0
    publish_layer_pointcloud_rate_hz: 5.0
    decay_tsdf_rate_hz: 5.0
    decay_dynamic_occupancy_rate_hz: 10.0
    clear_map_outside_radius_rate_hz: 1.0

    # printing statistics on console
    print_rates_to_console: true
    print_timings_to_console: true
    print_delays_to_console: true
    print_statistics_on_console_period_ms: 10000

    # esdf settings
    esdf_mode: 1 # 0: 3d, 1: 2d
    publish_esdf_distance_slice: true
    # color settings
    use_color: true
    # depth settings
    use_depth: true
    # lidar settings
    use_lidar: true
    lidar_width: 1800
    lidar_height: 31
    use_non_equal_vertical_fov_lidar_params: false
    # Input queues
    maximum_sensor_message_queue_length: 10
    # Map clearing settings
    map_clearing_radius_m: 7.0 # no map clearing if < 0.0
    map_clearing_frame_id: "base_link"
    # QoS settings
    input_qos: "SYSTEM_DEFAULT"
    # Rviz visualization
    slice_visualization_attachment_frame_id: "base_link"
    slice_visualization_side_length: 10.0

    layer_visualization_min_tsdf_weight: 0.1
    layer_visualization_max_tsdf_distance: 0.1
    layer_visualization_exclusion_height_m: 2.0
    layer_visualization_exclusion_radius_m: 7.0
    layer_visualization_undo_gamma_correction: false
    max_back_projection_distance: 7.0
    back_projection_subsampling: 1 # no subsampling if == 1

    static_mapper:
      # mapper
      maintain_mesh_block_stream_queue: true
      do_depth_preprocessing: false
      depth_preprocessing_num_dilations: 3
      # projective integrator (tsdf/color/occupancy)
      projective_integrator_max_integration_distance_m: 5.0
      projective_integrator_truncation_distance_vox: 4.0
      projective_integrator_weighting_mode: "inverse_square_tsdf_distance_penalty"
      projective_integrator_max_weight: 5.0
      # occupancy integrator
      free_region_occupancy_probability: 0.45
      occupied_region_occupancy_probability: 0.55
      unobserved_region_occupancy_probability: 0.5
      occupied_region_half_width_m: 0.1
      # esdf integrator
      esdf_integrator_min_weight: 0.1
      esdf_integrator_max_site_distance_vox: 5.0
      esdf_integrator_max_distance_m: 2.0
      # mesh integrator
      mesh_integrator_min_weight: 0.1
      mesh_integrator_weld_vertices: true
      # tsdf decay integrator
      tsdf_decay_factor: 0.95
      exclude_last_view_from_decay: true
      # mesh streamer
      mesh_streamer_exclusion_height_m: 2.0
      mesh_streamer_exclusion_radius_m: 7.0
      mesh_bandwidth_limit_mbps: 999999925.0 # in mega bits per second
