ARG BASE_IMAGE=nvblox_deps
ARG CMAKE_ARGS=""

FROM $BASE_IMAGE

SHELL ["/bin/bash", "-c"]

# Copy over nvblox
COPY . nvblox

# Build the standalone library
RUN cd nvblox/nvblox && mkdir build && cd build && \
    cmake .. $CMAKE_ARGS -DCMAKE_VERBOSE_MAKEFILE=1 && make -j8

# Build our python packages.
RUN cd nvblox && pip install --ignore-installed python/evaluation python/scripts python/common
