# # go2_description/config/rtabmap_core.yaml  (example)

rtabmap:
  ros__parameters:
    frame_id:            radar        # stays in YAML (no slash)
    subscribe_scan_cloud: true
    subscribe_depth:      false
    subscribe_rgb:        false
    sync_queue_size:      50
    topic_queue_size:     50
    approx_sync:          true
    wait_for_transform:   0.2
    use_sim_time:         false       # overridden in launch if needed


# rtabmap:
#   ros__parameters:
#     ## pure LiDAR / odom input
#     frame_id:             radar          # TF frame of your Unitree LiDAR
#     subscribe_scan_cloud: true
#     subscribe_depth:      false          # <-- must be false
#     subscribe_rgb:        false          # <-- must be false
#     approx_sync:          true
#     sync_queue_size:      50
#     topic_queue_size:     50
#     wait_for_transform:   0.2

#     ## ICP registration
#     Reg/Strategy:                   1     # ICP-only
#     Icp/PointToPlane:               true
#     Icp/VoxelSize:                  0.10
#     Icp/Iterations:                 15
#     Icp/MaxCorrespondenceDistance:  1.0

#     ## Occupancy-grid (2-D projection)
#     RGBD/CreateOccupancyGrid: true
#     Grid/3D:               false
#     Grid/RangeMax:         15.0
#     Grid/Resolution:       0.05

#     ## Memory / performance
#     Mem/STMSize:           30
#     Mem/NotLinkedNodesKept: false
