# Will be loaded _in addition_ to common_stereo.yaml + zedxm.yaml
---
/**:
  ros__parameters:
    pos_tracking:
        publish_tf:           false   # don’t broadcast map/odom/or base TF
        publish_map_tf:       false
        publish_odom_tf:      false
        # still compute the pose so topics /zed/zed_node/pose{,_with_covariance}
        # remain available if you ever want them
